# Generated by Django 4.2.5 on 2023-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_vehicle_geartype_remove_vehicle_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gear_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileagae',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
