# Generated by Django 4.2.5 on 2023-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_vehicle_engine_alter_vehicle_gear_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
