# Generated by Django 4.2.5 on 2023-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_vehicle_image1_alter_vehicle_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
