# Generated by Django 4.2.5 on 2023-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_vehicle_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
