# Generated by Django 4.2.5 on 2023-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_vehicle_model_vehicle_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_name',
            name='v_name',
            field=models.CharField(max_length=40),
        ),
    ]
