# Generated by Django 4.2.5 on 2023-10-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_vehicle_description_alter_vehicle_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='power',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
