# Generated by Django 4.2.5 on 2023-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_vehicle_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(),
        ),
    ]
