# Generated by Django 4.2.5 on 2023-10-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_vehicle_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='message',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='query',
            name='Your_question',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
